[package]
name = "transport_poc"

[targets.dart]
enabled = true
output = "dist/dart"

[targets.wasm]
enabled = true

[targets.wasm.optimize]
enabled = false

[targets.wasm.typescript]
output = "dist/wasm/generated"

[targets.wasm.npm]
output = "dist/wasm/dist"
package_name = "@transport-poc/wasm"
targets = ["nodejs"]
